CREATE TABLE IF NOT EXISTS ID_GNTR ( -- ID GENERATOR
    ID INT AUTO_INCREMENT,
    T_REF VARCHAR(30), -- table reference
    PRE_IDX VARCHAR(4), -- prefix index
    POST_IDX INT, -- postfix index
    CNO INT, -- current number
    PRIMARY KEY (ID)
);

INSERT INTO ID_GNTR (T_REF, PRE_IDX, POST_IDX, CNO) VALUES ("USER_CRD", "CRD", 101, 101);
INSERT INTO ID_GNTR (T_REF, PRE_IDX, POST_IDX, CNO) VALUES ("USR_CNT_DTLS", "CNT", 101, 101);

--ID      T_REF           PRE_IDX     PRE_IDX     CNO
--1       USER_CRD        CRD         101         101
--2       USR_CNT_DTLS    CNT         101         101


CREATE TABLE IF NOT EXISTS USER_CRD ( -- USER CREDENTIALS
    ID VARCHAR(30), -- ID TAKEN FROM ID_GNTR TABLE
    USERNAME VARCHAR(30), -- FULL NAME OF USER
    USER_ID VARCHAR(30), -- USERID FOR LOGIN
    E_PASSWORD VARCHAR(30), -- ENCRYPTED PASSWORD FOR SECURITY
    PRIMARY KEY (ID)
);

INSERT INTO USER_CRD VALUES ("CRD101101", "RAVI KUMAR PERURI", "RPERURI", "QWERTYUIOP");

CREATE TABLE IF NOT EXISTS USR_CNT_DTLS ( -- USER CONTACT DETAILS
    ID VARCHAR(30), -- ID TAKEN FROM ID_GNTR TABLE
    C_NAME VARCHAR(30), -- CONTACT NAME
    CONTACT_NO VARCHAR(15), -- CONTACT NUMBER
    EMAIL_ID VARCHAR(30), -- EMAIL-ID
    ADDRESS VARCHAR(100), -- ADDRESS FIELD
    PRIMARY KEY (ID)
);

INSERT INTO USR_CNT_DTLS VALUES ("CNT101101", "RAVI KUMAR PERURI", "07382133857", "ravi.peruri@gmail.com", Null);